# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 215c16b48a3046dea4c5b12ee7a1187b89801000693f6dfe3283ad5e16fdf7d94961c4a3ff65b8269a6077f12a269bc8b49e1bc182950bfdd91d46f2a7c1e3a8

test:
  secret_key_base: b1458d545a8478df7f9da49909b0e8f180a73ffc78bf8e4af670be2af5665d282a1c35f9f2bfd15b06e13a8b415bad717b9eb1b484783afa5d99e7b048b30216

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
